name: Build2 build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup build2
      uses: build2/setup-build2-github-action@v2
    - name: Create build configuration
      run:  bdep init -C @clang config.c=clang config.cxx=clang++ config.cxx.std=c++20
    - name: Compile
      run: b
      
