name: Build2 build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Libdpp .deb package
      run: wget -O dpp.deb https://dl.dpp.dev/
    - name: Install dep libopus
      run: sudo apt-get install -y libopus0
    - name: Install Libdpp
      run:  sudo dpkg -i dpp.deb
    - name: Setup Build2
      run:  wget https://download.build2.org/0.18.1/bindist/ubuntu/ubuntu24.04/x86_64/build2-toolchain_0.18.1-0~ubuntu24.04_amd64.deb
    - name: Sha256sum
      run:  wget https://download.build2.org/0.18.1/bindist/ubuntu/ubuntu24.04/x86_64/packages.sha256
    - name: SHA256 compare
      run:  sha256sum -c packages.sha256
    - name: Build2 install
      run:  sudo apt-get install ./build2-toolchain_0.18.1-0~ubuntu24.04_amd64.deb
    - name: Get source code
      uses: actions/checkout@v4
    - name: Create Build2 build configuration folder
      run:  mkdir ${GITHUB_WOKSPACE}/../clangDBG && cd ${GITHUB_WOKSPACE}/../clangDBG
    - name: Create Build2 build configuration
      run: bpkg create cc config.cxx=clang++ config.c=clang config.cxx.std=c++20
    - name: Initialize project in the new configuration
      run:  bdep init -A ${GITHUB_WORKSPACE}../clangDBG @clangDBG "sync ?sys:libdpp"
    - name: Compile
      run: b
      
